// lib/airport-data.ts
// Shared airport dataset and search utilities.
// Used by both the subscribe page and manage preferences page.

export interface Airport {
  code: string;
  name: string;
  city: string;
  state: string;
  lat: number;
  lon: number;
  dist?: number;
}

export const AIRPORTS: Airport[] = [
  // Northeast
  { code:'JFK', name:'John F. Kennedy Intl',              city:'New York',        state:'NY', lat:40.6413, lon:-73.7781 },
  { code:'LGA', name:'LaGuardia Airport',                  city:'New York',        state:'NY', lat:40.7772, lon:-73.8726 },
  { code:'EWR', name:'Newark Liberty Intl',                city:'Newark',          state:'NJ', lat:40.6895, lon:-74.1745 },
  { code:'BOS', name:'Logan Intl',                         city:'Boston',          state:'MA', lat:42.3656, lon:-71.0096 },
  { code:'PHL', name:'Philadelphia Intl',                  city:'Philadelphia',    state:'PA', lat:39.8721, lon:-75.2411 },
  { code:'BWI', name:'Baltimore/Washington Intl',          city:'Baltimore',       state:'MD', lat:39.1754, lon:-76.6682 },
  { code:'DCA', name:'Ronald Reagan Washington National',  city:'Washington',      state:'DC', lat:38.8512, lon:-77.0402 },
  { code:'IAD', name:'Washington Dulles Intl',             city:'Washington',      state:'DC', lat:38.9531, lon:-77.4565 },
  // Southeast
  { code:'ATL', name:'Hartsfield-Jackson Atlanta Intl',   city:'Atlanta',         state:'GA', lat:33.6407, lon:-84.4277 },
  { code:'MIA', name:'Miami Intl',                         city:'Miami',           state:'FL', lat:25.7959, lon:-80.2870 },
  { code:'FLL', name:'Fort Lauderdale-Hollywood Intl',    city:'Fort Lauderdale', state:'FL', lat:26.0726, lon:-80.1527 },
  { code:'MCO', name:'Orlando Intl',                       city:'Orlando',         state:'FL', lat:28.4312, lon:-81.3081 },
  { code:'TPA', name:'Tampa Intl',                         city:'Tampa',           state:'FL', lat:27.9755, lon:-82.5332 },
  { code:'CLT', name:'Charlotte Douglas Intl',             city:'Charlotte',       state:'NC', lat:35.2144, lon:-80.9473 },
  { code:'RDU', name:'Raleigh-Durham Intl',                city:'Raleigh',         state:'NC', lat:35.8776, lon:-78.7875 },
  { code:'BNA', name:'Nashville Intl',                     city:'Nashville',       state:'TN', lat:36.1263, lon:-86.6774 },
  // Midwest
  { code:'ORD', name:"O'Hare Intl",                        city:'Chicago',         state:'IL', lat:41.9742, lon:-87.9073 },
  { code:'MDW', name:'Chicago Midway Intl',                city:'Chicago',         state:'IL', lat:41.7868, lon:-87.7522 },
  { code:'DTW', name:'Detroit Metropolitan',               city:'Detroit',         state:'MI', lat:42.2162, lon:-83.3554 },
  { code:'MSP', name:'Minneapolis-Saint Paul Intl',        city:'Minneapolis',     state:'MN', lat:44.8848, lon:-93.2223 },
  { code:'CLE', name:'Cleveland Hopkins Intl',             city:'Cleveland',       state:'OH', lat:41.4117, lon:-81.8498 },
  { code:'CMH', name:'John Glenn Columbus Intl',           city:'Columbus',        state:'OH', lat:39.9980, lon:-82.8919 },
  { code:'IND', name:'Indianapolis Intl',                  city:'Indianapolis',    state:'IN', lat:39.7173, lon:-86.2944 },
  { code:'MKE', name:'General Mitchell Intl',              city:'Milwaukee',       state:'WI', lat:42.9472, lon:-87.8966 },
  { code:'STL', name:'St. Louis Lambert Intl',             city:'St. Louis',       state:'MO', lat:38.7487, lon:-90.3700 },
  { code:'MCI', name:'Kansas City Intl',                   city:'Kansas City',     state:'MO', lat:39.2976, lon:-94.7139 },
  { code:'OMA', name:'Eppley Airfield',                    city:'Omaha',           state:'NE', lat:41.3032, lon:-95.8940 },
  // Southwest
  { code:'DFW', name:'Dallas/Fort Worth Intl',             city:'Dallas',          state:'TX', lat:32.8998, lon:-97.0403 },
  { code:'DAL', name:'Dallas Love Field',                  city:'Dallas',          state:'TX', lat:32.8471, lon:-96.8518 },
  { code:'IAH', name:'George Bush Intercontinental',       city:'Houston',         state:'TX', lat:29.9902, lon:-95.3368 },
  { code:'HOU', name:'William P. Hobby',                   city:'Houston',         state:'TX', lat:29.6454, lon:-95.2789 },
  { code:'SAT', name:'San Antonio Intl',                   city:'San Antonio',     state:'TX', lat:29.5337, lon:-98.4698 },
  { code:'AUS', name:'Austin-Bergstrom Intl',              city:'Austin',          state:'TX', lat:30.1975, lon:-97.6664 },
  { code:'PHX', name:'Phoenix Sky Harbor Intl',            city:'Phoenix',         state:'AZ', lat:33.4373, lon:-112.0078 },
  { code:'TUS', name:'Tucson Intl',                        city:'Tucson',          state:'AZ', lat:32.1161, lon:-110.9410 },
  { code:'ABQ', name:'Albuquerque Intl Sunport',           city:'Albuquerque',     state:'NM', lat:35.0402, lon:-106.6090 },
  { code:'DEN', name:'Denver Intl',                        city:'Denver',          state:'CO', lat:39.8561, lon:-104.6737 },
  { code:'COS', name:'Colorado Springs Airport',           city:'Colorado Springs',state:'CO', lat:38.8059, lon:-104.7009 },
  { code:'SLC', name:'Salt Lake City Intl',                city:'Salt Lake City',  state:'UT', lat:40.7884, lon:-111.9778 },
  { code:'LAS', name:'Harry Reid Intl',                    city:'Las Vegas',       state:'NV', lat:36.0840, lon:-115.1537 },
  // West Coast
  { code:'LAX', name:'Los Angeles Intl',                   city:'Los Angeles',     state:'CA', lat:33.9425, lon:-118.4081 },
  { code:'BUR', name:'Hollywood Burbank Airport',          city:'Los Angeles',     state:'CA', lat:34.2007, lon:-118.3585 },
  { code:'LGB', name:'Long Beach Airport',                 city:'Los Angeles',     state:'CA', lat:33.8177, lon:-118.1516 },
  { code:'ONT', name:'Ontario Intl',                       city:'Los Angeles',     state:'CA', lat:34.0560, lon:-117.6012 },
  { code:'SNA', name:'John Wayne Airport',                 city:'Orange County',   state:'CA', lat:33.6757, lon:-117.8682 },
  { code:'SFO', name:'San Francisco Intl',                 city:'San Francisco',   state:'CA', lat:37.6213, lon:-122.3790 },
  { code:'OAK', name:'Oakland Intl',                       city:'Oakland',         state:'CA', lat:37.7213, lon:-122.2208 },
  { code:'SJC', name:'San Jose Mineta Intl',               city:'San Jose',        state:'CA', lat:37.3626, lon:-121.9290 },
  { code:'SAN', name:'San Diego Intl',                     city:'San Diego',       state:'CA', lat:32.7338, lon:-117.1933 },
  { code:'SEA', name:'Seattle-Tacoma Intl',                city:'Seattle',         state:'WA', lat:47.4502, lon:-122.3088 },
  { code:'PDX', name:'Portland Intl',                      city:'Portland',        state:'OR', lat:45.5898, lon:-122.5951 },
  // International
  { code:'CUN', name:'Cancún Intl',                        city:'Cancún',          state:'Mexico',      lat:21.0365, lon:-86.8771 },
  { code:'NAS', name:'Lynden Pindling Intl',               city:'Nassau',          state:'Bahamas',     lat:25.0390, lon:-77.4662 },
  { code:'MBJ', name:'Sangster Intl',                      city:'Montego Bay',     state:'Jamaica',     lat:18.5037, lon:-77.9134 },
  { code:'SJU', name:'Luis Muñoz Marín Intl',              city:'San Juan',        state:'Puerto Rico', lat:18.4394, lon:-66.0018 },
  { code:'LHR', name:'Heathrow Airport',                   city:'London',          state:'UK',          lat:51.4700, lon:-0.4543  },
  { code:'CDG', name:'Charles de Gaulle',                  city:'Paris',           state:'France',      lat:49.0097, lon:2.5479   },
  { code:'FCO', name:'Leonardo da Vinci Intl',             city:'Rome',            state:'Italy',       lat:41.8003, lon:12.2389  },
  { code:'BCN', name:'Barcelona El Prat',                  city:'Barcelona',       state:'Spain',       lat:41.2971, lon:2.0785   },
  { code:'AMS', name:'Amsterdam Schiphol',                 city:'Amsterdam',       state:'Netherlands', lat:52.3086, lon:4.7639   },
  { code:'NRT', name:'Narita Intl',                        city:'Tokyo',           state:'Japan',       lat:35.7720, lon:140.3929 },
  { code:'HND', name:'Haneda Airport',                     city:'Tokyo',           state:'Japan',       lat:35.5494, lon:139.7798 },
  { code:'ICN', name:'Incheon Intl',                       city:'Seoul',           state:'South Korea', lat:37.4602, lon:126.4407 },
  { code:'SYD', name:'Sydney Kingsford Smith',             city:'Sydney',          state:'Australia',   lat:-33.9461,lon:151.1772 },
  { code:'GRU', name:'São Paulo/Guarulhos Intl',           city:'São Paulo',       state:'Brazil',      lat:-23.4356,lon:-46.4731 },
  { code:'MEX', name:'Mexico City Intl',                   city:'Mexico City',     state:'Mexico',      lat:19.4363, lon:-99.0721 },
  // Northeast regionals
  { code:'PIT', name:'Pittsburgh Intl',                    city:'Pittsburgh',      state:'PA', lat:40.4915,  lon:-80.2329  },
  { code:'BUF', name:'Buffalo Niagara Intl',               city:'Buffalo',         state:'NY', lat:42.9405,  lon:-78.7322  },
  { code:'ALB', name:'Albany Intl',                        city:'Albany',          state:'NY', lat:42.7483,  lon:-73.8017  },
  { code:'SYR', name:'Syracuse Hancock Intl',              city:'Syracuse',        state:'NY', lat:43.1112,  lon:-76.1063  },
  { code:'ROC', name:'Greater Rochester Intl',             city:'Rochester',       state:'NY', lat:43.1189,  lon:-77.6724  },
  { code:'BDL', name:'Bradley Intl',                       city:'Hartford',        state:'CT', lat:41.9389,  lon:-72.6832  },
  { code:'PVD', name:'T.F. Green Intl',                    city:'Providence',      state:'RI', lat:41.7269,  lon:-71.4280  },
  { code:'MHT', name:'Manchester-Boston Regional',         city:'Manchester',      state:'NH', lat:42.9326,  lon:-71.4357  },
  { code:'BTV', name:'Burlington Intl',                    city:'Burlington',      state:'VT', lat:44.4720,  lon:-73.1533  },
  { code:'PWM', name:'Portland Intl Jetport',              city:'Portland',        state:'ME', lat:43.6462,  lon:-70.3093  },
  { code:'BGR', name:'Bangor Intl',                        city:'Bangor',          state:'ME', lat:44.8074,  lon:-68.8282  },
  { code:'ORF', name:'Norfolk Intl',                       city:'Norfolk',         state:'VA', lat:36.8976,  lon:-76.0122  },
  { code:'RIC', name:'Richmond Intl',                      city:'Richmond',        state:'VA', lat:37.5052,  lon:-77.3197  },
  { code:'ROA', name:'Roanoke-Blacksburg Regional',        city:'Roanoke',         state:'VA', lat:37.3255,  lon:-79.9754  },
  // Southeast regionals
  { code:'CHS', name:'Charleston Intl',                    city:'Charleston',      state:'SC', lat:32.8987,  lon:-80.0405  },
  { code:'GSP', name:'Greenville-Spartanburg Intl',        city:'Greenville',      state:'SC', lat:34.8957,  lon:-82.2189  },
  { code:'GSO', name:'Piedmont Triad Intl',                city:'Greensboro',      state:'NC', lat:36.0978,  lon:-79.9373  },
  { code:'ILM', name:'Wilmington Intl',                    city:'Wilmington',      state:'NC', lat:34.2706,  lon:-77.9026  },
  { code:'AVL', name:'Asheville Regional',                 city:'Asheville',       state:'NC', lat:35.4362,  lon:-82.5418  },
  { code:'SAV', name:'Savannah/Hilton Head Intl',          city:'Savannah',        state:'GA', lat:32.1276,  lon:-81.2021  },
  { code:'AGS', name:'Augusta Regional',                   city:'Augusta',         state:'GA', lat:33.3699,  lon:-81.9645  },
  { code:'JAX', name:'Jacksonville Intl',                  city:'Jacksonville',    state:'FL', lat:30.4941,  lon:-81.6879  },
  { code:'PNS', name:'Pensacola Intl',                     city:'Pensacola',       state:'FL', lat:30.4734,  lon:-87.1866  },
  { code:'VPS', name:'Destin-Fort Walton Beach Airport',   city:'Destin',          state:'FL', lat:30.4832,  lon:-86.5254  },
  { code:'ECP', name:'Northwest Florida Beaches Intl',     city:'Panama City Beach',state:'FL',lat:30.3572,  lon:-85.7963  },
  { code:'TLH', name:'Tallahassee Intl',                   city:'Tallahassee',     state:'FL', lat:30.3965,  lon:-84.3503  },
  { code:'GNV', name:'Gainesville Regional',               city:'Gainesville',     state:'FL', lat:29.6900,  lon:-82.2717  },
  { code:'DAB', name:'Daytona Beach Intl',                 city:'Daytona Beach',   state:'FL', lat:29.1799,  lon:-81.0581  },
  { code:'SRQ', name:'Sarasota-Bradenton Intl',            city:'Sarasota',        state:'FL', lat:27.3954,  lon:-82.5543  },
  { code:'RSW', name:'Southwest Florida Intl',             city:'Fort Myers',      state:'FL', lat:26.5362,  lon:-81.7552  },
  { code:'PIE', name:'St. Pete-Clearwater Intl',           city:'St. Petersburg',  state:'FL', lat:27.9102,  lon:-82.6874  },
  { code:'PBI', name:'Palm Beach Intl',                    city:'West Palm Beach', state:'FL', lat:26.6832,  lon:-80.0956  },
  { code:'EYW', name:'Key West Intl',                      city:'Key West',        state:'FL', lat:24.5561,  lon:-81.7596  },
  { code:'MEM', name:'Memphis Intl',                       city:'Memphis',         state:'TN', lat:35.0424,  lon:-89.9767  },
  { code:'TYS', name:'McGhee Tyson Airport',               city:'Knoxville',       state:'TN', lat:35.8128,  lon:-83.9940  },
  { code:'CHA', name:'Chattanooga Metropolitan',           city:'Chattanooga',     state:'TN', lat:35.0353,  lon:-85.2038  },
  { code:'TRI', name:'Tri-Cities Regional',                city:'Kingsport',       state:'TN', lat:36.4752,  lon:-82.4074  },
  { code:'HSV', name:'Huntsville Intl',                    city:'Huntsville',      state:'AL', lat:34.6372,  lon:-86.7751  },
  { code:'BHM', name:'Birmingham-Shuttlesworth Intl',      city:'Birmingham',      state:'AL', lat:33.5629,  lon:-86.7535  },
  { code:'MGM', name:'Montgomery Regional',                city:'Montgomery',      state:'AL', lat:32.3006,  lon:-86.3940  },
  { code:'MOB', name:'Mobile Regional',                    city:'Mobile',          state:'AL', lat:30.6913,  lon:-88.2428  },
  { code:'JAN', name:'Jackson-Medgar Wiley Evers Intl',    city:'Jackson',         state:'MS', lat:32.3112,  lon:-90.0759  },
  { code:'GPT', name:'Gulfport-Biloxi Intl',               city:'Gulfport',        state:'MS', lat:30.4073,  lon:-89.0701  },
  { code:'MSY', name:'Louis Armstrong New Orleans Intl',   city:'New Orleans',     state:'LA', lat:29.9934,  lon:-90.2580  },
  { code:'BTR', name:'Baton Rouge Metropolitan',           city:'Baton Rouge',     state:'LA', lat:30.5332,  lon:-91.1496  },
  { code:'LFT', name:'Lafayette Regional',                 city:'Lafayette',       state:'LA', lat:30.2053,  lon:-91.9876  },
  { code:'SHV', name:'Shreveport Regional',                city:'Shreveport',      state:'LA', lat:32.4466,  lon:-93.8256  },
  { code:'LIT', name:'Bill and Hillary Clinton Natl',      city:'Little Rock',     state:'AR', lat:34.7294,  lon:-92.2243  },
  { code:'XNA', name:'Northwest Arkansas National',        city:'Fayetteville',    state:'AR', lat:36.2819,  lon:-94.3068  },
  // Midwest regionals
  { code:'CVG', name:'Cincinnati/Northern Kentucky Intl',  city:'Cincinnati',      state:'OH', lat:39.0488,  lon:-84.6678  },
  { code:'DAY', name:'Dayton Intl',                        city:'Dayton',          state:'OH', lat:39.9024,  lon:-84.2194  },
  { code:'TOL', name:'Toledo Express',                     city:'Toledo',          state:'OH', lat:41.5868,  lon:-83.8078  },
  { code:'SDF', name:'Louisville Muhammed Ali Intl',       city:'Louisville',      state:'KY', lat:38.1744,  lon:-85.7360  },
  { code:'LEX', name:'Blue Grass Airport',                 city:'Lexington',       state:'KY', lat:38.0365,  lon:-84.6059  },
  { code:'GRR', name:'Gerald R. Ford Intl',                city:'Grand Rapids',    state:'MI', lat:42.8808,  lon:-85.5228  },
  { code:'LAN', name:'Capital Region Intl',                city:'Lansing',         state:'MI', lat:42.7787,  lon:-84.5874  },
  { code:'TVC', name:'Cherry Capital Airport',             city:'Traverse City',   state:'MI', lat:44.7414,  lon:-85.5822  },
  { code:'FWA', name:'Fort Wayne Intl',                    city:'Fort Wayne',      state:'IN', lat:40.9785,  lon:-85.1953  },
  { code:'SBN', name:'South Bend Intl',                    city:'South Bend',      state:'IN', lat:41.7087,  lon:-86.3173  },
  { code:'EVV', name:'Evansville Regional',                city:'Evansville',      state:'IN', lat:38.0369,  lon:-87.5324  },
  { code:'MSN', name:'Dane County Regional',               city:'Madison',         state:'WI', lat:43.1399,  lon:-89.3375  },
  { code:'GRB', name:'Green Bay Austin Straubel Intl',     city:'Green Bay',       state:'WI', lat:44.4851,  lon:-88.1296  },
  { code:'DSM', name:'Des Moines Intl',                    city:'Des Moines',      state:'IA', lat:41.5340,  lon:-93.6630  },
  { code:'CID', name:'Eastern Iowa Airport',               city:'Cedar Rapids',    state:'IA', lat:41.8842,  lon:-91.7108  },
  { code:'ICT', name:'Wichita Dwight D. Eisenhower Natl',  city:'Wichita',         state:'KS', lat:37.6499,  lon:-97.4330  },
  { code:'SGF', name:'Springfield-Branson National',       city:'Springfield',     state:'MO', lat:37.2457,  lon:-93.3888  },
  { code:'FAR', name:'Hector Intl',                        city:'Fargo',           state:'ND', lat:46.9207,  lon:-96.8158  },
  { code:'BIS', name:'Bismarck Municipal',                 city:'Bismarck',        state:'ND', lat:46.7724,  lon:-100.7467 },
  { code:'FSD', name:'Sioux Falls Regional',               city:'Sioux Falls',     state:'SD', lat:43.5820,  lon:-96.7418  },
  { code:'RAP', name:'Rapid City Regional',                city:'Rapid City',      state:'SD', lat:44.0453,  lon:-103.0574 },
  // Mountain / Plains
  { code:'OKC', name:'Will Rogers World Airport',          city:'Oklahoma City',   state:'OK', lat:35.3931,  lon:-97.6007  },
  { code:'TUL', name:'Tulsa Intl',                         city:'Tulsa',           state:'OK', lat:36.1984,  lon:-95.8881  },
  { code:'BIL', name:'Billings Logan Intl',                city:'Billings',        state:'MT', lat:45.8077,  lon:-108.5428 },
  { code:'MSO', name:'Missoula Montana Airport',           city:'Missoula',        state:'MT', lat:46.9163,  lon:-114.0906 },
  { code:'BZN', name:'Bozeman Yellowstone Intl',           city:'Bozeman',         state:'MT', lat:45.7775,  lon:-111.1603 },
  { code:'GTF', name:'Great Falls Intl',                   city:'Great Falls',     state:'MT', lat:47.4820,  lon:-111.3711 },
  { code:'HLN', name:'Helena Regional',                    city:'Helena',          state:'MT', lat:46.6066,  lon:-111.9830 },
  { code:'FCA', name:'Glacier Park Intl',                  city:'Kalispell',       state:'MT', lat:48.3105,  lon:-114.2557 },
  { code:'ASE', name:'Aspen-Pitkin County Airport',        city:'Aspen',           state:'CO', lat:39.2232,  lon:-106.8689 },
  { code:'EGE', name:'Eagle County Regional',              city:'Vail',            state:'CO', lat:39.6426,  lon:-106.9178 },
  { code:'GJT', name:'Grand Junction Regional',            city:'Grand Junction',  state:'CO', lat:39.1224,  lon:-108.5267 },
  { code:'DRO', name:'Durango-La Plata County Airport',    city:'Durango',         state:'CO', lat:37.1515,  lon:-107.7538 },
  { code:'BOI', name:'Boise Airport',                      city:'Boise',           state:'ID', lat:43.5644,  lon:-116.2228 },
  { code:'IDA', name:'Idaho Falls Regional',               city:'Idaho Falls',     state:'ID', lat:43.5146,  lon:-112.0702 },
  { code:'TWF', name:'Magic Valley Regional',              city:'Twin Falls',      state:'ID', lat:42.4818,  lon:-114.4877 },
  // Texas regionals
  { code:'ELP', name:'El Paso Intl',                       city:'El Paso',         state:'TX', lat:31.8072,  lon:-106.3779 },
  { code:'LBB', name:'Lubbock Preston Smith Intl',         city:'Lubbock',         state:'TX', lat:33.6636,  lon:-101.8228 },
  { code:'MAF', name:'Midland Intl Air & Space Port',      city:'Midland',         state:'TX', lat:31.9425,  lon:-102.2029 },
  { code:'AMA', name:'Rick Husband Amarillo Intl',         city:'Amarillo',        state:'TX', lat:35.2194,  lon:-101.7061 },
  { code:'CRP', name:'Corpus Christi Intl',                city:'Corpus Christi',  state:'TX', lat:27.7704,  lon:-97.5017  },
  { code:'HRL', name:'Valley Intl',                        city:'Harlingen',       state:'TX', lat:26.2285,  lon:-97.6540  },
  { code:'MFE', name:'McAllen Miller Intl',                city:'McAllen',         state:'TX', lat:26.1758,  lon:-98.2386  },
  { code:'LRD', name:'Laredo Intl',                        city:'Laredo',          state:'TX', lat:27.5438,  lon:-99.4614  },
  { code:'ACT', name:'Waco Regional',                      city:'Waco',            state:'TX', lat:31.6113,  lon:-97.2305  },
  // West Coast regionals
  { code:'GEG', name:'Spokane Intl',                       city:'Spokane',         state:'WA', lat:47.6199,  lon:-117.5339 },
  { code:'BLI', name:'Bellingham Intl',                    city:'Bellingham',      state:'WA', lat:48.7928,  lon:-122.5375 },
  { code:'YKM', name:'Yakima Air Terminal',                city:'Yakima',          state:'WA', lat:46.5682,  lon:-120.5439 },
  { code:'RNO', name:'Reno-Tahoe Intl',                    city:'Reno',            state:'NV', lat:39.4991,  lon:-119.7681 },
  { code:'SMF', name:'Sacramento Intl',                    city:'Sacramento',      state:'CA', lat:38.6954,  lon:-121.5908 },
  { code:'FAT', name:'Fresno Yosemite Intl',               city:'Fresno',          state:'CA', lat:36.7762,  lon:-119.7181 },
  { code:'SBA', name:'Santa Barbara Airport',              city:'Santa Barbara',   state:'CA', lat:34.4262,  lon:-119.8400 },
  { code:'MRY', name:'Monterey Regional',                  city:'Monterey',        state:'CA', lat:36.5870,  lon:-121.8428 },
  { code:'PSP', name:'Palm Springs Intl',                  city:'Palm Springs',    state:'CA', lat:33.8297,  lon:-116.5067 },
  { code:'BFL', name:'Meadows Field',                      city:'Bakersfield',     state:'CA', lat:35.4336,  lon:-119.0568 },
  { code:'SBP', name:'San Luis Obispo County Regional',    city:'San Luis Obispo', state:'CA', lat:35.2377,  lon:-120.6434 },
  { code:'RDD', name:'Redding Municipal',                  city:'Redding',         state:'CA', lat:40.5090,  lon:-122.2932 },
  { code:'MFR', name:'Rogue Valley Intl-Medford',          city:'Medford',         state:'OR', lat:42.3742,  lon:-122.8735 },
  { code:'EUG', name:'Eugene Airport',                     city:'Eugene',          state:'OR', lat:44.1246,  lon:-123.2119 },
  { code:'RDM', name:'Roberts Field',                      city:'Bend',            state:'OR', lat:44.2541,  lon:-121.1501 },
  // Alaska
  { code:'ANC', name:'Ted Stevens Anchorage Intl',         city:'Anchorage',       state:'AK', lat:61.1741,  lon:-149.9961 },
  { code:'FAI', name:'Fairbanks Intl',                     city:'Fairbanks',       state:'AK', lat:64.8154,  lon:-147.8561 },
  { code:'JNU', name:'Juneau Intl',                        city:'Juneau',          state:'AK', lat:58.3550,  lon:-134.5763 },
  { code:'KTN', name:'Ketchikan Intl',                     city:'Ketchikan',       state:'AK', lat:55.3556,  lon:-131.7137 },
  { code:'SIT', name:'Sitka Rocky Gutierrez Airport',      city:'Sitka',           state:'AK', lat:57.0471,  lon:-135.3616 },
  { code:'HOM', name:'Homer Airport',                      city:'Homer',           state:'AK', lat:59.6456,  lon:-151.4775 },
  // Hawaii
  { code:'HNL', name:'Daniel K. Inouye Intl',              city:'Honolulu',        state:'HI', lat:21.3245,  lon:-157.9251 },
  { code:'OGG', name:'Kahului Airport',                    city:'Maui',            state:'HI', lat:20.8986,  lon:-156.4305 },
  { code:'KOA', name:'Ellison Onizuka Kona Intl',          city:'Kona',            state:'HI', lat:19.7388,  lon:-156.0456 },
  { code:'LIH', name:'Lihue Airport',                      city:'Lihue',           state:'HI', lat:21.9760,  lon:-159.3388 },
  { code:'ITO', name:'Hilo Intl',                          city:'Hilo',            state:'HI', lat:19.7214,  lon:-155.0485 },
  // Caribbean / Mexico additions
  { code:'SJD', name:'Los Cabos Intl',                     city:'Los Cabos',       state:'Mexico',            lat:23.1518,  lon:-109.7216 },
  { code:'PVR', name:'Licenciado Gustavo Diaz Ordaz Intl', city:'Puerto Vallarta', state:'Mexico',            lat:20.6801,  lon:-105.2544 },
  { code:'GDL', name:'Miguel Hidalgo y Costilla Intl',     city:'Guadalajara',     state:'Mexico',            lat:20.5218,  lon:-103.3106 },
  { code:'PUJ', name:'Punta Cana Intl',                    city:'Punta Cana',      state:'Dominican Republic',lat:18.5674,  lon:-68.3634  },
  { code:'AUA', name:'Queen Beatrix Intl',                  city:'Aruba',           state:'Aruba',             lat:12.5014,  lon:-70.0152  },
  { code:'BGI', name:'Grantley Adams Intl',                city:'Bridgetown',      state:'Barbados',          lat:13.0746,  lon:-59.4925  },
  { code:'SXM', name:'Princess Juliana Intl',              city:'Sint Maarten',    state:'Sint Maarten',      lat:18.0410,  lon:-63.1089  },
  { code:'BQN', name:'Rafael Hernandez Airport',           city:'Aguadilla',       state:'Puerto Rico',       lat:18.4949,  lon:-67.1294  },
  // Europe additions
  { code:'DUB', name:'Dublin Airport',                     city:'Dublin',          state:'Ireland',           lat:53.4213,  lon:-6.2700   },
  { code:'MAD', name:'Adolfo Suarez Madrid-Barajas',       city:'Madrid',          state:'Spain',             lat:40.4719,  lon:-3.5626   },
  { code:'FRA', name:'Frankfurt Airport',                  city:'Frankfurt',       state:'Germany',           lat:50.0379,  lon:8.5622    },
  { code:'MUC', name:'Munich Airport',                     city:'Munich',          state:'Germany',           lat:48.3537,  lon:11.7750   },
  { code:'ZRH', name:'Zurich Airport',                     city:'Zurich',          state:'Switzerland',       lat:47.4647,  lon:8.5492    },
  { code:'CPH', name:'Copenhagen Airport',                 city:'Copenhagen',      state:'Denmark',           lat:55.6181,  lon:12.6561   },
  { code:'ATH', name:'Athens Intl',                        city:'Athens',          state:'Greece',            lat:37.9364,  lon:23.9445   },
  { code:'LIS', name:'Humberto Delgado Airport',           city:'Lisbon',          state:'Portugal',          lat:38.7813,  lon:-9.1359   },
  { code:'IST', name:'Istanbul Airport',                   city:'Istanbul',        state:'Turkey',            lat:41.2608,  lon:28.7418   },
  // Middle East / Asia / Other
  { code:'DXB', name:'Dubai Intl',                         city:'Dubai',           state:'UAE',               lat:25.2532,  lon:55.3657   },
  { code:'DOH', name:'Hamad Intl',                         city:'Doha',            state:'Qatar',             lat:25.2731,  lon:51.6086   },
  { code:'SIN', name:'Singapore Changi',                   city:'Singapore',       state:'Singapore',         lat:1.3644,   lon:103.9915  },
  { code:'BKK', name:'Suvarnabhumi Airport',               city:'Bangkok',         state:'Thailand',          lat:13.6900,  lon:100.7501  },
  { code:'HKG', name:'Hong Kong Intl',                     city:'Hong Kong',       state:'Hong Kong',         lat:22.3080,  lon:113.9185  },
  { code:'PVG', name:'Shanghai Pudong Intl',               city:'Shanghai',        state:'China',             lat:31.1434,  lon:121.8052  },
  { code:'DEL', name:'Indira Gandhi Intl',                 city:'Delhi',           state:'India',             lat:28.5665,  lon:77.1031   },
  { code:'BOM', name:'Chhatrapati Shivaji Maharaj Intl',   city:'Mumbai',          state:'India',             lat:19.0896,  lon:72.8656   },
  // Canada
  { code:'YYZ', name:'Toronto Pearson Intl',               city:'Toronto',         state:'Canada',            lat:43.6777,  lon:-79.6248  },
  { code:'YVR', name:'Vancouver Intl',                     city:'Vancouver',       state:'Canada',            lat:49.1967,  lon:-123.1815 },
  { code:'YUL', name:'Montréal-Trudeau Intl',              city:'Montreal',        state:'Canada',            lat:45.4706,  lon:-73.7408  },
  { code:'YYC', name:'Calgary Intl',                       city:'Calgary',         state:'Canada',            lat:51.1139,  lon:-114.0203 },
  // South America
  { code:'GIG', name:'Rio de Janeiro Galeão Intl',         city:'Rio de Janeiro',  state:'Brazil',            lat:-22.8099, lon:-43.2505  },
  { code:'EZE', name:'Ministro Pistarini Intl',            city:'Buenos Aires',    state:'Argentina',         lat:-34.8222, lon:-58.5358  },
  { code:'SCL', name:'Arturo Merino Benítez Intl',         city:'Santiago',        state:'Chile',             lat:-33.3930, lon:-70.7858  },
  { code:'LIM', name:'Jorge Chávez Intl',                  city:'Lima',            state:'Peru',              lat:-12.0219, lon:-77.1143  },
  { code:'BOG', name:'El Dorado Intl',                     city:'Bogota',          state:'Colombia',          lat:4.7016,   lon:-74.1469  },
];

export const ROADTRIP_CITIES: string[] = [
  // Alabama
  'Birmingham, AL', 'Montgomery, AL', 'Huntsville, AL', 'Mobile, AL', 'Tuscaloosa, AL',
  'Auburn, AL', 'Decatur, AL', 'Gulf Shores, AL', 'Fairhope, AL', 'Florence, AL',
  // Alaska
  'Anchorage, AK', 'Fairbanks, AK', 'Juneau, AK', 'Sitka, AK', 'Ketchikan, AK',
  'Homer, AK', 'Seward, AK', 'Talkeetna, AK', 'Kenai, AK',
  // Arizona
  'Phoenix, AZ', 'Tucson, AZ', 'Mesa, AZ', 'Chandler, AZ', 'Scottsdale, AZ',
  'Flagstaff, AZ', 'Sedona, AZ', 'Prescott, AZ', 'Tempe, AZ', 'Yuma, AZ',
  'Lake Havasu City, AZ', 'Page, AZ', 'Williams, AZ',
  // Arkansas
  'Little Rock, AR', 'Fort Smith, AR', 'Fayetteville, AR', 'Springdale, AR',
  'Jonesboro, AR', 'Conway, AR', 'Rogers, AR', 'Hot Springs, AR', 'Eureka Springs, AR',
  // California
  'Los Angeles, CA', 'San Diego, CA', 'San Jose, CA', 'San Francisco, CA',
  'Fresno, CA', 'Sacramento, CA', 'Long Beach, CA', 'Oakland, CA', 'Bakersfield, CA',
  'Anaheim, CA', 'Santa Ana, CA', 'Riverside, CA', 'Stockton, CA', 'Irvine, CA',
  'Santa Rosa, CA', 'Oceanside, CA', 'Salinas, CA', 'Sunnyvale, CA',
  'Pasadena, CA', 'Escondido, CA', 'Torrance, CA', 'Fullerton, CA', 'Visalia, CA',
  'Thousand Oaks, CA', 'Simi Valley, CA', 'Berkeley, CA', 'Costa Mesa, CA',
  'Santa Barbara, CA', 'Napa, CA', 'Redding, CA', 'Santa Cruz, CA',
  'Carmel-by-the-Sea, CA', 'Lake Tahoe, CA', 'Palm Springs, CA', 'Monterey, CA',
  'Napa Valley, CA', 'Sonoma, CA', 'Healdsburg, CA', 'San Luis Obispo, CA',
  'Big Sur, CA', 'Malibu, CA', 'Laguna Beach, CA', 'Santa Monica, CA',
  'Ventura, CA', 'Redlands, CA', 'Temecula, CA',
  // Colorado
  'Denver, CO', 'Colorado Springs, CO', 'Aurora, CO', 'Fort Collins, CO',
  'Lakewood, CO', 'Thornton, CO', 'Arvada, CO', 'Westminster, CO', 'Pueblo, CO',
  'Boulder, CO', 'Aspen, CO', 'Vail, CO', 'Telluride, CO', 'Steamboat Springs, CO',
  'Breckenridge, CO', 'Durango, CO', 'Glenwood Springs, CO', 'Estes Park, CO',
  'Crested Butte, CO', 'Ouray, CO', 'Salida, CO', 'Silverton, CO',
  // Connecticut
  'Bridgeport, CT', 'New Haven, CT', 'Hartford, CT', 'Stamford, CT',
  'Waterbury, CT', 'Norwalk, CT', 'Danbury, CT', 'New Britain, CT',
  'Greenwich, CT', 'Mystic, CT', 'Essex, CT', 'Litchfield, CT',
  // Delaware
  'Wilmington, DE', 'Dover, DE', 'Newark, DE', 'Rehoboth Beach, DE',
  'Lewes, DE', 'Milford, DE',
  // Florida
  'Jacksonville, FL', 'Miami, FL', 'Tampa, FL', 'Orlando, FL',
  'St. Petersburg, FL', 'Tallahassee, FL', 'Fort Lauderdale, FL',
  'Cape Coral, FL', 'Pembroke Pines, FL', 'Hollywood, FL', 'Clearwater, FL',
  'West Palm Beach, FL', 'Lakeland, FL', 'Coral Springs, FL', 'Boca Raton, FL',
  'Pompano Beach, FL', 'Gainesville, FL', 'Plantation, FL', 'Sunrise, FL',
  'Key West, FL', 'Destin, FL', 'Naples, FL', 'Sarasota, FL', 'Fort Myers, FL',
  'Daytona Beach, FL', 'St. Augustine, FL', 'Pensacola, FL', 'Ocala, FL',
  'Panama City Beach, FL', 'Sanibel Island, FL', 'Clearwater Beach, FL',
  'Miami Beach, FL', 'Islamorada, FL', 'Siesta Key, FL', 'Amelia Island, FL',
  // Georgia
  'Atlanta, GA', 'Augusta, GA', 'Columbus, GA', 'Macon, GA', 'Savannah, GA',
  'Athens, GA', 'Sandy Springs, GA', 'Roswell, GA', 'Albany, GA',
  'Warner Robins, GA', 'Alpharetta, GA', 'Marietta, GA', 'Valdosta, GA',
  'Tybee Island, GA', 'Blue Ridge, GA', 'Dahlonega, GA', 'Helen, GA',
  'Jekyll Island, GA', 'St. Simons Island, GA',
  // Hawaii
  'Honolulu, HI', 'Hilo, HI', 'Kailua, HI', 'Pearl City, HI', 'Waipahu, HI',
  'Kaneohe, HI', 'Kihei, HI', 'Lahaina, HI', 'Lihue, HI', 'Kona, HI',
  'Waikiki, HI', 'Hana, HI', 'Lanai City, HI', 'Molokai, HI',
  // Idaho
  'Boise, ID', 'Meridian, ID', 'Nampa, ID', 'Idaho Falls, ID', 'Pocatello, ID',
  'Caldwell, ID', "Coeur d'Alene, ID", 'Twin Falls, ID', 'Lewiston, ID',
  'Sun Valley, ID', 'McCall, ID', 'Sandpoint, ID',
  // Illinois
  'Chicago, IL', 'Aurora, IL', 'Joliet, IL', 'Naperville, IL', 'Rockford, IL',
  'Springfield, IL', 'Elgin, IL', 'Peoria, IL', 'Champaign, IL', 'Waukegan, IL',
  'Bloomington, IL', 'Evanston, IL', 'Decatur, IL', 'Schaumburg, IL',
  'Galena, IL', 'Starved Rock, IL', 'Galesburg, IL', 'Quincy, IL',
  // Indiana
  'Indianapolis, IN', 'Fort Wayne, IN', 'Evansville, IN', 'South Bend, IN',
  'Carmel, IN', 'Hammond, IN', 'Fishers, IN', 'Bloomington, IN',
  'Gary, IN', 'Lafayette, IN', 'Muncie, IN', 'Terre Haute, IN',
  'Brown County, IN', 'Nashville, IN', 'French Lick, IN',
  // Iowa
  'Des Moines, IA', 'Cedar Rapids, IA', 'Davenport, IA', 'Sioux City, IA',
  'Iowa City, IA', 'Waterloo, IA', 'Council Bluffs, IA', 'Dubuque, IA',
  'Ames, IA', 'Cedar Falls, IA',
  // Kansas
  'Wichita, KS', 'Overland Park, KS', 'Kansas City, KS', 'Topeka, KS',
  'Olathe, KS', 'Lawrence, KS', 'Shawnee, KS', 'Manhattan, KS', 'Lenexa, KS',
  'Dodge City, KS', 'Abilene, KS',
  // Kentucky
  'Louisville, KY', 'Lexington, KY', 'Bowling Green, KY', 'Owensboro, KY',
  'Covington, KY', 'Richmond, KY', 'Georgetown, KY', 'Florence, KY',
  'Henderson, KY', 'Elizabethtown, KY', 'Bardstown, KY', 'Mammoth Cave, KY',
  'Berea, KY', 'Paducah, KY',
  // Louisiana
  'New Orleans, LA', 'Baton Rouge, LA', 'Shreveport, LA', 'Lafayette, LA',
  'Lake Charles, LA', 'Kenner, LA', 'Bossier City, LA', 'Monroe, LA',
  'Alexandria, LA', 'Natchitoches, LA', 'Grand Isle, LA',
  // Maine
  'Portland, ME', 'Lewiston, ME', 'Bangor, ME', 'South Portland, ME',
  'Auburn, ME', 'Augusta, ME', 'Bar Harbor, ME', 'Acadia, ME',
  'Kennebunkport, ME', 'Ogunquit, ME', 'Camden, ME', 'Freeport, ME',
  // Maryland
  'Baltimore, MD', 'Columbia, MD', 'Germantown, MD', 'Silver Spring, MD',
  'Frederick, MD', 'Rockville, MD', 'Gaithersburg, MD', 'Bethesda, MD',
  'Annapolis, MD', 'Ocean City, MD', 'Easton, MD', 'St. Michaels, MD',
  'Chesapeake City, MD',
  // Massachusetts
  'Boston, MA', 'Worcester, MA', 'Springfield, MA', 'Lowell, MA',
  'Cambridge, MA', 'Brockton, MA', 'New Bedford, MA', 'Fall River, MA',
  'Lynn, MA', 'Quincy, MA', 'Newton, MA', 'Somerville, MA', 'Framingham, MA',
  'Nantucket, MA', "Martha's Vineyard, MA", 'Cape Cod, MA', 'Plymouth, MA',
  'Salem, MA', 'Gloucester, MA', 'Provincetown, MA', 'Lenox, MA', 'Stockbridge, MA',
  // Michigan
  'Detroit, MI', 'Grand Rapids, MI', 'Warren, MI', 'Sterling Heights, MI',
  'Ann Arbor, MI', 'Lansing, MI', 'Flint, MI', 'Dearborn, MI', 'Livonia, MI',
  'Troy, MI', 'Farmington Hills, MI', 'Kalamazoo, MI', 'Wyoming, MI',
  'Traverse City, MI', 'Mackinac Island, MI', 'Petoskey, MI', 'Harbor Springs, MI',
  'Sleeping Bear Dunes, MI', 'Pictured Rocks, MI', 'Marquette, MI',
  // Minnesota
  'Minneapolis, MN', 'Saint Paul, MN', 'Rochester, MN', 'Bloomington, MN',
  'Duluth, MN', 'Brooklyn Park, MN', 'Plymouth, MN', 'Maple Grove, MN',
  'Woodbury, MN', 'St. Cloud, MN', 'Eagan, MN', 'Mankato, MN',
  'Brainerd, MN', 'Walker, MN', 'Ely, MN', 'Grand Marais, MN',
  // Mississippi
  'Jackson, MS', 'Gulfport, MS', 'Southaven, MS', 'Hattiesburg, MS',
  'Biloxi, MS', 'Meridian, MS', 'Tupelo, MS', 'Greenville, MS',
  'Natchez, MS', 'Ocean Springs, MS', 'Oxford, MS',
  // Missouri
  'Kansas City, MO', 'St. Louis, MO', 'Springfield, MO', 'Columbia, MO',
  'Independence, MO', "Lee's Summit, MO", "O'Fallon, MO", 'St. Joseph, MO',
  'St. Charles, MO', 'Branson, MO', 'Hannibal, MO', 'Hermann, MO',
  // Montana
  'Billings, MT', 'Missoula, MT', 'Great Falls, MT', 'Bozeman, MT',
  'Butte, MT', 'Helena, MT', 'Kalispell, MT', 'Whitefish, MT',
  'Glacier National Park, MT', 'Livingston, MT', 'Big Sky, MT',
  // Nebraska
  'Omaha, NE', 'Lincoln, NE', 'Bellevue, NE', 'Grand Island, NE',
  'Kearney, NE', 'Fremont, NE', 'Norfolk, NE', 'North Platte, NE',
  // Nevada
  'Las Vegas, NV', 'Henderson, NV', 'Reno, NV', 'North Las Vegas, NV',
  'Sparks, NV', 'Carson City, NV', 'Elko, NV', 'Lake Tahoe, NV',
  // New Hampshire
  'Manchester, NH', 'Nashua, NH', 'Concord, NH', 'Dover, NH', 'Rochester, NH',
  'Salem, NH', 'Keene, NH', 'Portsmouth, NH', 'North Conway, NH',
  'Franconia Notch, NH', 'Laconia, NH', 'Hanover, NH',
  // New Jersey
  'Newark, NJ', 'Jersey City, NJ', 'Paterson, NJ', 'Elizabeth, NJ',
  'Edison, NJ', 'Woodbridge, NJ', 'Toms River, NJ', 'Hamilton, NJ',
  'Trenton, NJ', 'Clifton, NJ', 'Camden, NJ', 'Brick, NJ', 'Cherry Hill, NJ',
  'Atlantic City, NJ', 'Cape May, NJ', 'Princeton, NJ', 'Hoboken, NJ',
  'Asbury Park, NJ', 'Spring Lake, NJ',
  // New Mexico
  'Albuquerque, NM', 'Las Cruces, NM', 'Rio Rancho, NM', 'Santa Fe, NM',
  'Roswell, NM', 'Farmington, NM', 'Clovis, NM', 'Hobbs, NM', 'Taos, NM',
  'White Sands, NM', 'Carlsbad, NM', 'Silver City, NM',
  // New York
  'New York City, NY', 'Buffalo, NY', 'Rochester, NY', 'Yonkers, NY',
  'Syracuse, NY', 'Albany, NY', 'New Rochelle, NY', 'Schenectady, NY',
  'Utica, NY', 'Niagara Falls, NY', 'Troy, NY', 'White Plains, NY',
  'Saratoga Springs, NY', 'Ithaca, NY', 'Lake Placid, NY', 'Hudson, NY',
  'Catskills, NY', 'Finger Lakes, NY', 'Hamptons, NY', 'Sag Harbor, NY',
  'Montauk, NY', 'Fire Island, NY',
  // North Carolina
  'Charlotte, NC', 'Raleigh, NC', 'Greensboro, NC', 'Durham, NC',
  'Winston-Salem, NC', 'Fayetteville, NC', 'Cary, NC', 'Wilmington, NC',
  'High Point, NC', 'Concord, NC', 'Asheville, NC', 'Greenville, NC',
  'Gastonia, NC', 'Chapel Hill, NC', 'Outer Banks, NC', 'Boone, NC',
  'Blowing Rock, NC', 'Brevard, NC', 'Blue Ridge Parkway, NC', 'Highlands, NC',
  // North Dakota
  'Fargo, ND', 'Bismarck, ND', 'Grand Forks, ND', 'Minot, ND',
  'West Fargo, ND', 'Williston, ND', 'Medora, ND',
  // Ohio
  'Columbus, OH', 'Cleveland, OH', 'Cincinnati, OH', 'Toledo, OH',
  'Akron, OH', 'Dayton, OH', 'Parma, OH', 'Canton, OH', 'Youngstown, OH',
  'Lorain, OH', 'Hamilton, OH', 'Springfield, OH', 'Kettering, OH',
  'Elyria, OH', 'Mansfield, OH', 'Newark, OH', 'Athens, OH',
  'Hocking Hills, OH', 'Sandusky, OH', 'Put-in-Bay, OH',
  // Oklahoma
  'Oklahoma City, OK', 'Tulsa, OK', 'Norman, OK', 'Broken Arrow, OK',
  'Lawton, OK', 'Edmond, OK', 'Moore, OK', 'Midwest City, OK',
  'Enid, OK', 'Stillwater, OK', 'Tahlequah, OK',
  // Oregon
  'Portland, OR', 'Salem, OR', 'Eugene, OR', 'Gresham, OR', 'Hillsboro, OR',
  'Beaverton, OR', 'Bend, OR', 'Medford, OR', 'Springfield, OR', 'Corvallis, OR',
  'Ashland, OR', 'Astoria, OR', 'Cannon Beach, OR', 'Hood River, OR',
  'Crater Lake, OR', 'Bandon, OR', 'Sisters, OR',
  // Pennsylvania
  'Philadelphia, PA', 'Pittsburgh, PA', 'Allentown, PA', 'Erie, PA',
  'Reading, PA', 'Scranton, PA', 'Bethlehem, PA', 'Lancaster, PA',
  'Harrisburg, PA', 'Altoona, PA', 'York, PA', 'State College, PA',
  'Gettysburg, PA', 'Valley Forge, PA', 'New Hope, PA', 'Pocono Mountains, PA',
  'Hershey, PA', 'Intercourse, PA',
  // Rhode Island
  'Providence, RI', 'Warwick, RI', 'Cranston, RI', 'Pawtucket, RI',
  'East Providence, RI', 'Woonsocket, RI', 'Newport, RI', 'Block Island, RI',
  'Narragansett, RI',
  // South Carolina
  'Columbia, SC', 'Charleston, SC', 'North Charleston, SC', 'Mount Pleasant, SC',
  'Rock Hill, SC', 'Greenville, SC', 'Summerville, SC', 'Goose Creek, SC',
  'Hilton Head Island, SC', 'Myrtle Beach, SC', 'Florence, SC', 'Spartanburg, SC',
  'Beaufort, SC', 'Folly Beach, SC', 'Pawleys Island, SC',
  // South Dakota
  'Sioux Falls, SD', 'Rapid City, SD', 'Aberdeen, SD', 'Brookings, SD',
  'Watertown, SD', 'Mitchell, SD', 'Yankton, SD', 'Pierre, SD',
  'Badlands, SD', 'Deadwood, SD', 'Hot Springs, SD', 'Custer, SD',
  // Tennessee
  'Nashville, TN', 'Memphis, TN', 'Knoxville, TN', 'Chattanooga, TN',
  'Clarksville, TN', 'Murfreesboro, TN', 'Franklin, TN', 'Jackson, TN',
  'Johnson City, TN', 'Kingsport, TN', 'Morristown, TN', 'Gatlinburg, TN',
  'Pigeon Forge, TN', 'Sevierville, TN', 'Jonesborough, TN',
  // Texas
  'Houston, TX', 'San Antonio, TX', 'Dallas, TX', 'Austin, TX', 'Fort Worth, TX',
  'El Paso, TX', 'Arlington, TX', 'Corpus Christi, TX', 'Plano, TX',
  'Laredo, TX', 'Lubbock, TX', 'Garland, TX', 'Irving, TX', 'Frisco, TX',
  'McKinney, TX', 'Amarillo, TX', 'Grand Prairie, TX', 'Brownsville, TX',
  'Killeen, TX', 'Pasadena, TX', 'Mesquite, TX', 'McAllen, TX', 'Waco, TX',
  'Carrollton, TX', 'Denton, TX', 'Midland, TX', 'Abilene, TX',
  'Beaumont, TX', 'Round Rock, TX', 'Galveston, TX', 'Port Arthur, TX',
  'San Marcos, TX', 'Marfa, TX', 'Fredericksburg, TX', 'Gruene, TX',
  'New Braunfels, TX', 'Wimberley, TX', 'Bastrop, TX',
  // Utah
  'Salt Lake City, UT', 'West Valley City, UT', 'Provo, UT', 'West Jordan, UT',
  'Orem, UT', 'Sandy, UT', 'St. George, UT', 'Ogden, UT', 'Logan, UT',
  'Moab, UT', 'Park City, UT', 'Bryce Canyon, UT', 'Zion, UT',
  'Arches, UT', 'Capitol Reef, UT', 'Canyonlands, UT', 'Cedar City, UT',
  'Torrey, UT',
  // Vermont
  'Burlington, VT', 'South Burlington, VT', 'Rutland, VT', 'Barre, VT',
  'Montpelier, VT', 'Stowe, VT', 'Brattleboro, VT', 'Woodstock, VT',
  'Manchester, VT', 'Middlebury, VT', 'Killington, VT',
  // Virginia
  'Virginia Beach, VA', 'Norfolk, VA', 'Chesapeake, VA', 'Richmond, VA',
  'Newport News, VA', 'Alexandria, VA', 'Hampton, VA', 'Roanoke, VA',
  'Portsmouth, VA', 'Suffolk, VA', 'Lynchburg, VA', 'Harrisonburg, VA',
  'Charlottesville, VA', 'Arlington, VA', 'Fredericksburg, VA', 'Williamsburg, VA',
  'Shenandoah, VA', 'Luray, VA', 'Blue Ridge Parkway, VA', 'Abingdon, VA',
  'Chincoteague, VA',
  // Washington
  'Seattle, WA', 'Spokane, WA', 'Tacoma, WA', 'Vancouver, WA', 'Bellevue, WA',
  'Kent, WA', 'Everett, WA', 'Renton, WA', 'Kirkland, WA', 'Bellingham, WA',
  'Kennewick, WA', 'Yakima, WA', 'Redmond, WA', 'Olympia, WA',
  'Leavenworth, WA', 'Winthrop, WA', 'Chelan, WA', 'Port Townsend, WA',
  'San Juan Islands, WA', 'Mount Rainier, WA', 'North Cascades, WA',
  // West Virginia
  'Charleston, WV', 'Huntington, WV', 'Parkersburg, WV', 'Morgantown, WV',
  'Wheeling, WV', 'Weirton, WV', "Harpers Ferry, WV", 'Lewisburg, WV',
  // Wisconsin
  'Milwaukee, WI', 'Madison, WI', 'Green Bay, WI', 'Kenosha, WI',
  'Racine, WI', 'Appleton, WI', 'Waukesha, WI', 'Oshkosh, WI',
  'Eau Claire, WI', 'Janesville, WI', 'La Crosse, WI', 'Door County, WI',
  'Wisconsin Dells, WI', 'Bayfield, WI', 'Apostle Islands, WI',
  // Wyoming
  'Cheyenne, WY', 'Casper, WY', 'Laramie, WY', 'Gillette, WY',
  'Rock Springs, WY', 'Jackson Hole, WY', 'Cody, WY', 'Sheridan, WY',
  'Yellowstone, WY', 'Grand Teton, WY',
];

export const AIRLINES: string[] = [
  'Any airline', 'American', 'Delta', 'United', 'Southwest', 'JetBlue',
  'Alaska', 'Spirit', 'Frontier', 'Allegiant', 'Hawaiian', 'Sun Country',
];

// City centroid lookup for haversine-based nearby airport search
export const CITY_COORDS: Record<string, { lat: number; lon: number }> = {
  'new york':       { lat:40.7128,  lon:-74.0060  },
  'chicago':        { lat:41.8781,  lon:-87.6298  },
  'los angeles':    { lat:34.0522,  lon:-118.2437 },
  'miami':          { lat:25.7617,  lon:-80.1918  },
  'dallas':         { lat:32.7767,  lon:-96.7970  },
  'houston':        { lat:29.7604,  lon:-95.3698  },
  'atlanta':        { lat:33.7490,  lon:-84.3880  },
  'seattle':        { lat:47.6062,  lon:-122.3321 },
  'denver':         { lat:39.7392,  lon:-104.9903 },
  'boston':         { lat:42.3601,  lon:-71.0589  },
  'san francisco':  { lat:37.7749,  lon:-122.4194 },
  'phoenix':        { lat:33.4484,  lon:-112.0740 },
  'washington':     { lat:38.9072,  lon:-77.0369  },
  'philadelphia':   { lat:39.9526,  lon:-75.1652  },
  'las vegas':      { lat:36.1699,  lon:-115.1398 },
  'minneapolis':    { lat:44.9778,  lon:-93.2650  },
  'detroit':        { lat:42.3314,  lon:-83.0458  },
  'portland':       { lat:45.5051,  lon:-122.6750 },
  'salt lake city': { lat:40.7608,  lon:-111.8910 },
  'orlando':        { lat:28.5383,  lon:-81.3792  },
  'nashville':      { lat:36.1627,  lon:-86.7816  },
  'charlotte':      { lat:35.2271,  lon:-80.8431  },
  'austin':         { lat:30.2672,  lon:-97.7431  },
  'san diego':      { lat:32.7157,  lon:-117.1611 },
  'tampa':          { lat:27.9506,  lon:-82.4572  },
  'baltimore':      { lat:39.2904,  lon:-76.6122  },
  'kansas city':    { lat:39.0997,  lon:-94.5786  },
  'st. louis':      { lat:38.6270,  lon:-90.1994  },
  'cleveland':      { lat:41.4993,  lon:-81.6944  },
  'columbus':       { lat:39.9612,  lon:-82.9988  },
  'indianapolis':   { lat:39.7684,  lon:-86.1581  },
  'milwaukee':      { lat:43.0389,  lon:-87.9065  },
  'omaha':          { lat:41.2565,  lon:-95.9345  },
  'cancún':         { lat:21.1619,  lon:-86.8515  },
  'cancun':         { lat:21.1619,  lon:-86.8515  },
  'london':         { lat:51.5074,  lon:-0.1278   },
  'paris':          { lat:48.8566,  lon:2.3522    },
  'rome':           { lat:41.9028,  lon:12.4964   },
  'tokyo':          { lat:35.6762,  lon:139.6503  },
  'barcelona':      { lat:41.3851,  lon:2.1734    },
  'amsterdam':      { lat:52.3676,  lon:4.9041    },
  'sydney':         { lat:-33.8688, lon:151.2093  },
  'seoul':          { lat:37.5665,  lon:126.9780  },
  'mexico city':    { lat:19.4326,  lon:-99.1332  },
  'san juan':       { lat:18.4655,  lon:-66.1057  },
  'nassau':         { lat:25.0443,  lon:-77.3504  },
  'montego bay':    { lat:18.4762,  lon:-77.8939  },
  'fort lauderdale':{ lat:26.1224,  lon:-80.1373  },
  'newark':         { lat:40.7357,  lon:-74.1724  },
  'san antonio':    { lat:29.4241,  lon:-98.4936  },
  'tucson':         { lat:32.2226,  lon:-110.9747 },
  'albuquerque':    { lat:35.0844,  lon:-106.6504 },
  // Northeast regionals
  'pittsburgh':     { lat:40.4406,  lon:-79.9959  },
  'buffalo':        { lat:42.8864,  lon:-78.8784  },
  'albany':         { lat:42.6526,  lon:-73.7562  },
  'syracuse':       { lat:43.0481,  lon:-76.1474  },
  'rochester':      { lat:43.1566,  lon:-77.6088  },
  'hartford':       { lat:41.7658,  lon:-72.6851  },
  'providence':     { lat:41.8240,  lon:-71.4128  },
  'manchester':     { lat:42.9956,  lon:-71.4548  },
  'burlington':     { lat:44.4759,  lon:-73.2121  },
  'norfolk':        { lat:36.8508,  lon:-76.2859  },
  'richmond':       { lat:37.5407,  lon:-77.4360  },
  'roanoke':        { lat:37.2710,  lon:-79.9414  },
  // Southeast regionals
  'charleston':     { lat:32.7765,  lon:-79.9311  },
  'savannah':       { lat:32.0835,  lon:-81.0998  },
  'jacksonville':   { lat:30.3322,  lon:-81.6557  },
  'pensacola':      { lat:30.4213,  lon:-87.2169  },
  'tallahassee':    { lat:30.4518,  lon:-84.2807  },
  'gainesville':    { lat:29.6516,  lon:-82.3248  },
  'daytona beach':  { lat:29.2108,  lon:-81.0228  },
  'sarasota':       { lat:27.3364,  lon:-82.5307  },
  'fort myers':     { lat:26.6406,  lon:-81.8723  },
  'west palm beach':{ lat:26.7153,  lon:-80.0534  },
  'key west':       { lat:24.5551,  lon:-81.7800  },
  'memphis':        { lat:35.1495,  lon:-90.0490  },
  'knoxville':      { lat:35.9606,  lon:-83.9207  },
  'chattanooga':    { lat:35.0456,  lon:-85.3097  },
  'huntsville':     { lat:34.7304,  lon:-86.5861  },
  'birmingham':     { lat:33.5186,  lon:-86.8104  },
  'montgomery':     { lat:32.3668,  lon:-86.2999  },
  'mobile':         { lat:30.6954,  lon:-88.0399  },
  'jackson':        { lat:32.2988,  lon:-90.1848  },
  'gulfport':       { lat:30.3674,  lon:-89.0928  },
  'new orleans':    { lat:29.9511,  lon:-90.0715  },
  'baton rouge':    { lat:30.4515,  lon:-91.1871  },
  'shreveport':     { lat:32.5252,  lon:-93.7502  },
  'little rock':    { lat:34.7465,  lon:-92.2896  },
  'fayetteville':   { lat:36.0626,  lon:-94.1574  },
  'greenville':     { lat:34.8526,  lon:-82.3940  },
  'greensboro':     { lat:36.0726,  lon:-79.7920  },
  'wilmington':     { lat:34.2257,  lon:-77.9447  },
  'asheville':      { lat:35.5951,  lon:-82.5515  },
  // Midwest regionals
  'cincinnati':     { lat:39.1031,  lon:-84.5120  },
  'dayton':         { lat:39.7589,  lon:-84.1916  },
  'toledo':         { lat:41.6639,  lon:-83.5552  },
  'louisville':     { lat:38.2527,  lon:-85.7585  },
  'lexington':      { lat:38.0406,  lon:-84.5037  },
  'grand rapids':   { lat:42.9634,  lon:-85.6681  },
  'lansing':        { lat:42.7325,  lon:-84.5555  },
  'traverse city':  { lat:44.7631,  lon:-85.6206  },
  'fort wayne':     { lat:41.0793,  lon:-85.1394  },
  'south bend':     { lat:41.6764,  lon:-86.2520  },
  'evansville':     { lat:37.9716,  lon:-87.5711  },
  'madison':        { lat:43.0731,  lon:-89.4012  },
  'green bay':      { lat:44.5133,  lon:-88.0133  },
  'des moines':     { lat:41.5868,  lon:-93.6250  },
  'cedar rapids':   { lat:41.9779,  lon:-91.6656  },
  'wichita':        { lat:37.6872,  lon:-97.3301  },
  'springfield':    { lat:37.2090,  lon:-93.2923  },
  'fargo':          { lat:46.8772,  lon:-96.7898  },
  'bismarck':       { lat:46.8083,  lon:-100.7837 },
  'sioux falls':    { lat:43.5446,  lon:-96.7311  },
  'rapid city':     { lat:44.0805,  lon:-103.2310 },
  // Mountain / Plains
  'oklahoma city':  { lat:35.4676,  lon:-97.5164  },
  'tulsa':          { lat:36.1540,  lon:-95.9928  },
  'billings':       { lat:45.7833,  lon:-108.5007 },
  'missoula':       { lat:46.8787,  lon:-113.9966 },
  'bozeman':        { lat:45.6770,  lon:-111.0429 },
  'great falls':    { lat:47.5002,  lon:-111.3008 },
  'helena':         { lat:46.5958,  lon:-112.0270 },
  'kalispell':      { lat:48.1920,  lon:-114.3129 },
  'aspen':          { lat:39.1911,  lon:-106.8175 },
  'grand junction': { lat:39.0639,  lon:-108.5506 },
  'durango':        { lat:37.2753,  lon:-107.8801 },
  'boise':          { lat:43.6150,  lon:-116.2023 },
  'idaho falls':    { lat:43.4917,  lon:-112.0334 },
  'twin falls':     { lat:42.5630,  lon:-114.4609 },
  // Texas regionals
  'el paso':        { lat:31.7619,  lon:-106.4850 },
  'lubbock':        { lat:33.5779,  lon:-101.8552 },
  'midland':        { lat:31.9974,  lon:-102.0779 },
  'amarillo':       { lat:35.2220,  lon:-101.8313 },
  'corpus christi': { lat:27.8006,  lon:-97.3964  },
  'harlingen':      { lat:26.1906,  lon:-97.6961  },
  'mcallen':        { lat:26.2034,  lon:-98.2300  },
  'laredo':         { lat:27.5064,  lon:-99.5075  },
  'waco':           { lat:31.5493,  lon:-97.1467  },
  // West Coast regionals
  'spokane':        { lat:47.6588,  lon:-117.4260 },
  'bellingham':     { lat:48.7519,  lon:-122.4787 },
  'yakima':         { lat:46.6021,  lon:-120.5059 },
  'reno':           { lat:39.5296,  lon:-119.8138 },
  'sacramento':     { lat:38.5816,  lon:-121.4944 },
  'fresno':         { lat:36.7378,  lon:-119.7871 },
  'bakersfield':    { lat:35.3733,  lon:-119.0187 },
  'santa barbara':  { lat:34.4208,  lon:-119.6982 },
  'monterey':       { lat:36.6002,  lon:-121.8947 },
  'palm springs':   { lat:33.8303,  lon:-116.5453 },
  'san luis obispo':{ lat:35.2828,  lon:-120.6596 },
  'redding':        { lat:40.5865,  lon:-122.3917 },
  'medford':        { lat:42.3265,  lon:-122.8756 },
  'eugene':         { lat:44.0521,  lon:-123.0868 },
  'bend':           { lat:44.0582,  lon:-121.3153 },
  // Alaska
  'anchorage':      { lat:61.2181,  lon:-149.9003 },
  'fairbanks':      { lat:64.8378,  lon:-147.7164 },
  'juneau':         { lat:58.3005,  lon:-134.4197 },
  // Hawaii
  'honolulu':       { lat:21.3069,  lon:-157.8583 },
  'maui':           { lat:20.7984,  lon:-156.3319 },
  'kona':           { lat:19.6395,  lon:-155.9969 },
  'hilo':           { lat:19.7297,  lon:-155.0900 },
  // Caribbean / Mexico additions
  'los cabos':      { lat:23.1053,  lon:-109.8574 },
  'puerto vallarta':{ lat:20.6534,  lon:-105.2253 },
  'guadalajara':    { lat:20.6597,  lon:-103.3496 },
  'punta cana':     { lat:18.5601,  lon:-68.3725  },
  // Canada
  'toronto':        { lat:43.6532,  lon:-79.3832  },
  'vancouver':      { lat:49.2827,  lon:-123.1207 },
  'montreal':       { lat:45.5017,  lon:-73.5673  },
  'calgary':        { lat:51.0447,  lon:-114.0719 },
  // Europe additions
  'dublin':         { lat:53.3498,  lon:-6.2603   },
  'madrid':         { lat:40.4168,  lon:-3.7038   },
  'frankfurt':      { lat:50.1109,  lon:8.6821    },
  'munich':         { lat:48.1351,  lon:11.5820   },
  'zurich':         { lat:47.3769,  lon:8.5417    },
  'copenhagen':     { lat:55.6761,  lon:12.5683   },
  'athens':         { lat:37.9838,  lon:23.7275   },
  'lisbon':         { lat:38.7223,  lon:-9.1393   },
  'istanbul':       { lat:41.0082,  lon:28.9784   },
  // Middle East / Asia / Other
  'dubai':          { lat:25.2048,  lon:55.2708   },
  'doha':           { lat:25.2854,  lon:51.5310   },
  'singapore':      { lat:1.3521,   lon:103.8198  },
  'bangkok':        { lat:13.7563,  lon:100.5018  },
  'hong kong':      { lat:22.3193,  lon:114.1694  },
  'shanghai':       { lat:31.2304,  lon:121.4737  },
  'delhi':          { lat:28.7041,  lon:77.1025   },
  'mumbai':         { lat:19.0760,  lon:72.8777   },
  // South America
  'rio de janeiro': { lat:-22.9068, lon:-43.1729  },
  'buenos aires':   { lat:-34.6037, lon:-58.3816  },
  'santiago':       { lat:-33.4489, lon:-70.6693  },
  'lima':           { lat:-12.0464, lon:-77.0428  },
  'bogota':         { lat:4.7110,   lon:-74.0721  },
};

// Haversine distance in miles between two lat/lon points
export function haversine(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 3958.8;
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) * Math.sin(dLon / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

// Find airports near a typed city name (within 100 miles)
export function searchAirportsByCity(query: string): Airport[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];

  const cityCoords = CITY_COORDS[q];
  if (cityCoords) {
    return AIRPORTS
      .map(a => ({ ...a, dist: haversine(cityCoords.lat, cityCoords.lon, a.lat, a.lon) }))
      .filter(a => (a.dist ?? Infinity) <= 100)
      .sort((a, b) => (a.dist ?? 0) - (b.dist ?? 0));
  }

  // Fallback: fuzzy match on city, name, code, or state
  return AIRPORTS.filter(a =>
    a.city.toLowerCase().includes(q) ||
    a.name.toLowerCase().includes(q) ||
    a.code.toLowerCase().includes(q) ||
    a.state.toLowerCase().includes(q)
  ).slice(0, 8);
}

// Find road trip cities matching a query string
export function searchRoadtripCities(query: string): string[] {
  const q = query.toLowerCase().trim();
  if (q.length < 2) return [];
  return ROADTRIP_CITIES.filter(c => c.toLowerCase().includes(q)).slice(0, 8);
}
